spring:
  application:
    name: TRAINER-WORKLOAD-SERVICE


  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainersummary



  cloud:
    config:
      enabled: false

  jms:
    listener:
      auto-startup: true

#  activemq:
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
#
#    packages:
#      trust-all: true

jwt:
  token:
    header: Authorization




security:
  jwt:
    secret-key: dGhpcyBpcyBteSBzZWN1cmUga2V5IGFuZCB5b3UgY2Fubm90IGhhY2sgaXQ=



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082